tasks:
- ssh-keys: null
- ceph-ansible: null
- parallel:
    - rgw-system-test:
        test: Mbuckets_with_Nobjects
        script: test_Mbuckets_with_Nobjects.py
        clients: [client.0]
        config:
          user_count: 5
          bucket_count: 5
          objects_count: 20
          objects_size_range:
            min: 100
            max: 200
          test_ops:
            create_bucket: true
            create_object: true
            download_object: true
            delete_bucket_object: true
            sharding:
              enable: false
              max_shards: 0
            compression:
              enable: false
              type: zlib
    - rgw-system-test:
        test: Mbuckets_with_Nobjects_multipart
        script: test_Mbuckets_with_Nobjects.py
        clients: ['client.1']
        config:
          user_count: 2
          bucket_count: 5
          objects_count: 10
          objects_size_range:
            min: 1000
            max: 1500
          test_ops:
            create_bucket: true
            create_object: true
            download_object: true
            delete_bucket_object: true
            upload_type: multipart
            sharding:
              enable: false
              max_shards: 0
            compression:
              enable: false
              type: zlib
    - rgw-system-test:
        test: versioning_ops
        script: test_versioning_with_objects.py
        clients: ['client.0']
        config:
          user_count: 2
          bucket_count: 2
          objects_count: 10
          version_count: 5
          objects_size_range:
            min: 50
            max: 80
          test_ops:
            enable_version: true
            suspend_version: true
            copy_to_version: false
            delete_object_versions: false
            upload_after_suspend: true
    - rgw-system-test:
        test: versioning_ops_delete
        script: test_versioning_with_objects.py
        clients: ['client.1']
        config:
          user_count: 2
          bucket_count: 2
          objects_count: 10
          version_count: 5
          objects_size_range:
            min: 50
            max: 80
          test_ops:
            enable_version: true
            suspend_version: false
            copy_to_version: false
            delete_object_versions: true
            upload_after_suspend: false
